version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: careerhub-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: careerhub-backend
    depends_on:
      - db
      - redis
    restart: always
    image: dnevskiy/careerhub_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/

  redis:
    container_name: careerhub-redis
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    container_name: careerhub-celery
    image: dnevskiy/careerhub_backend
    hostname: worker
    entrypoint: celery
    command: -A core.celery.celery_app.app worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis


  frontend:
    container_name: careerhub-frontend
    depends_on:
      - backend
    image: dnevskiy/careerhub_frontend
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/app/dist/

  nginx:
    container_name: careerhub-nginx
    depends_on:
      - frontend
    restart: always
    image: dnevskiy/careerhub_nginx
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - "8500:80"